name: MERN CI

on:
  push:
    branches: [ main ]

jobs:
  mongo-init-test:
    runs-on: ubuntu-latest

    env:
      PORT: ${{ secrets.PORT }}
      MONGO_URI: ${{ secrets.MONGO_URI }}

    services:
      mongo:
        image: mongo:latest
        ports: ['27017:27017']

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Wait for Mongo to be ready
        run: |
          until nc -z localhost 27017; do 
            echo "Waiting for MongoDB to be ready..."
            sleep 2 
          done
          echo "MongoDB is ready"

      - name: Seed MongoDB
        working-directory: ./backend
        run: |
          npm install
          node seedTasksData.js

      - name: Run Tests
        working-directory: ./backend
        run: npm run test

